### ISSUE TITLE
issue with openstack VIM driver for brent

### ISSUE THREAD

**Issue by visomwa1** [accanto-systems/openstack-vim-driver#42]
Installed VIM driver successfully but while accessing the browser link getting below ,

error: Internal Server Error
UI : http://9.46.65.22:31681/api/infrastructure/ui

Deployment : 
root@eli4-master:~/vimdriver# helm install os-vim-driver-0.5.0.tgz --name os-vim-driver -f custom-values.yml --tls
NAME:   os-vim-driver
LAST DEPLOYED: Thu Feb 20 02:34:12 2020
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/Ingress
NAME                   HOSTS   ADDRESS  PORTS  AGE
os-vim-driver-ingress  ovd.lm  80       0s

==> v1/Pod(related)
NAME                           READY  STATUS             RESTARTS  AGE
os-vim-driver-7d54b6494-mkxsg  0/1    ContainerCreating  0         0s

==> v1/ConfigMap
NAME               DATA  AGE
os-vim-driver      1     1s
os-vim-driver-env  5     1s

==> v1/Service
NAME           TYPE      CLUSTER-IP  EXTERNAL-IP  PORT(S)         AGE
os-vim-driver  NodePort  10.0.67.97  <none>       8292:31681/TCP  1s

==> v1beta1/Deployment
NAME           DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
os-vim-driver  1        1        1           0          0s

Description of pods:
root@eli4-master:~/vimdriver# kubectl describe pods os-vim-driver-7d54b6494-mkxsg
Name:               os-vim-driver-7d54b6494-mkxsg
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               9.46.74.117/9.46.74.117
Start Time:         Thu, 20 Feb 2020 02:34:13 -0800
Labels:             app=os-vim-driver
                    part-of=lm
                    pod-template-hash=7d54b6494
Annotations:        kubernetes.io/psp: ibm-privileged-psp
Status:             Running
IP:                 10.1.49.185
Controlled By:      ReplicaSet/os-vim-driver-7d54b6494
Containers:
  os-vim-driver:
    Container ID:   docker://6485dfc85ada5f1e6a3af0f185aa4bdc84f39a3ccf8b15ee2484c7931ba6e02f
    Image:          accanto/os-vim-driver:0.5.0
    Image ID:       docker-pullable://accanto/os-vim-driver@sha256:17329933e415456b67c3cc4b9c407e494ff6ed2a3044e50605d5221210cd632f
    Port:           8292/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Thu, 20 Feb 2020 02:34:30 -0800
    Ready:          True
    Restart Count:  0
    Environment Variables from:
      os-vim-driver-env  ConfigMap  Optional: false
    Environment:         <none>
    Mounts:
      /var/ovd/ovd_config.yml from config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-mvd2r (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      os-vim-driver
    Optional:  false
  default-token-mvd2r:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-mvd2r
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                  Message
  ----    ------     ----  ----                  -------
  Normal  Scheduled  81s   default-scheduler     Successfully assigned default/os-vim-driver-7d54b6494-mkxsg to 9.46.74.117
  Normal  Pulling    78s   kubelet, 9.46.74.117  pulling image "accanto/os-vim-driver:0.5.0"
  Normal  Pulled     66s   kubelet, 9.46.74.117  Successfully pulled image "accanto/os-vim-driver:0.5.0"
  Normal  Created    64s   kubelet, 9.46.74.117  Created container
  Normal  Started    64s   kubelet, 9.46.74.117  Started container

Error logs : 
h", "thread_name": "MainThread", "level": "ERROR", "logger_name": "kafka.conn"}
{"@timestamp": "2020-02-20T10:34:33.915Z", "@version": "1", "message": "<BrokerConnection node_id=bootstrap-0 host=9.46.65.22:9092 <connecting> [IPv4 ('9.46.65.22', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED", "host": "os-vim-driver-7d54b6494-mkxsg", "path": "/usr/local/lib/python3.7/site-packages/kafka/conn.py", "tags": [], "type": "logstash", "thread_name": "MainThread", "level": "INFO", "logger_name": "kafka.conn"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/osvimdriver/__init__.py", line 12, in create_wsgi_app
    ignition_app = create_app()
  File "/usr/local/lib/python3.7/site-packages/osvimdriver/app.py", line 33, in create_app
    return app_builder.configure()
  File "/usr/local/lib/python3.7/site-packages/ignition/boot/api.py", line 127, in configure
    return BootstrapRunner(configuration).init_app()
  File "/usr/local/lib/python3.7/site-packages/ignition/boot/app.py", line 131, in init_app
    service_configurator.configure(self.configuration, self.service_register)
  File "/usr/local/lib/python3.7/site-packages/ignition/boot/configurators/jobqueue.py", line 36, in configure
    TopicCreator().create_topic_if_needed(messaging_config.connection_address, messaging_config.topics.job_queue)
  File "/usr/local/lib/python3.7/site-packages/ignition/service/messaging.py", line 62, in create_topic_if_needed
    admin_client = KafkaAdminClient(bootstrap_servers=connection_address, client_id='ignition')
  File "/usr/local/lib/python3.7/site-packages/kafka/admin/client.py", line 204, in __init__
    **self.config)
  File "/usr/local/lib/python3.7/site-packages/kafka/client_async.py", line 240, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/usr/local/lib/python3.7/site-packages/kafka/client_async.py", line 899, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9)
spawned uWSGI worker 1 (pid: 10, cores: 2)
spawned uWSGI worker 2 (pid: 12, cores: 2)
spawned uWSGI worker 3 (pid: 14, cores: 2)
spawned uWSGI worker 4 (pid: 16, cores: 2)
spawned uWSGI http 1 (pid: 18)
--- no python application found, check your startup logs for errors ---
[pid: 16|app: -1|req: -1/1] 10.1.157.192 () {38 vars in 3671 bytes} [Thu Feb 20 10:36:41 2020] GET /api/infrastructure/ui => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 14|app: -1|req: -1/2] 10.1.157.192 () {38 vars in 3592 bytes} [Thu Feb 20 10:36:41 2020] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 14|app: -1|req: -1/3] 10.1.157.192 () {40 vars in 3702 bytes} [Thu Feb 20 10:36:55 2020] GET /api/infrastructure/ui => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 10|app: -1|req: -1/4] 10.1.157.192 () {38 vars in 3592 bytes} [Thu Feb 20 10:36:55 2020] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)

## may be issue with kafka , 
As kafka is running on ClusterIp service and vim driver is running on NodePort : 

root@eli4-master:~/vimdriver# kubectl get svc |egrep -i "kafka|os-vim-driver"
alm-kafka           ClusterIP   None           <none>        9092/TCP,9093/TCP,8080/TCP,8443/TCP            27h
os-vim-driver       NodePort    10.0.67.97     <none>        8292:31681/TCP                                 6m49s

Questions : Do we need to change the kafka service to from ClusterIp to NodePort to access it from outside the K8S cluster ?

**Comment by sglover** [comment]
Hi, it could be that you'll need to open a NodePort for Kafka and update the custom-values.yml file to point to that. Is your VIM driver running in the same K8s cluster as your Kafka? What is in your custom-values.yml file?

**Comment by visomwa1** [comment]
Hi,

VIM driver and kafka is running in same K8S cluster.
root@eli4-master:~/vimdriver# cat custom-values.yml 
app:
  config:
    override:
      messaging:
        connection_address: "9.46.65.22:9092"

can you guide us to change kafka service from ClusterIp to NodePort.

**Comment by sglover** [comment]
If they're both running in the same K8s namespace, the driver should be able to connect directly to Kafka using the K8s network (there should be no need for a NodePort). Is 9.46.65.22 the IP address on the K8s network of one of the Kafka pods?

**Comment by visomwa1** [comment]
Hi, 

9.46.65.22 is IP of k8s master node, 
you want me to set the ip adress of one of the worker node where the kafka is running ( I.e part of k8s cluster) in custom-value.yaml file.. And then recreate vim-driver service

**Comment by dvaccarosenna** [comment]
Hi, 
As they are running in the same cluster, you should try `<kafka service name>:9092`. In your environment I believe this would be:
```
app:
  config:
    override:
      messaging:
        connection_address: "alm-kafka:9092"
```

Update your helm values with this then re-install the Openstack VIM driver.

**Comment by visomwa1** [comment]
Hi, 

Thanks it's worked for me..

**Comment by dvaccarosenna** [comment]
Closing this issue as "wontfix" as it has been resolved without code changes.
