### ISSUE TITLE
Support openstack certificates

### ISSUE THREAD

**Issue by joschkappel** [accanto-systems/openstack-vim-driver#43]
Production openstack environments issue a CA cert to secure the connection.
The deployment location MST be able to reference the CA cert (see OS_CACERT property in https://docs.openstack.org/python-openstackclient/pike/cli/man/openstack.html ).

**Comment by dvaccarosenna** [comment]
Hi Jochen, 
To be clear, is it only the OS_CACERT you need to be able to set? Or the OS_CERT and OS_KEY as well?

**Comment by joschkappel** [comment]
Up to now I only came across the needs to set the OS_CACERT.
