### ISSUE TITLE
Docs: Deployment Location - Use of string, e.g. os_cacert in deployment location

### ISSUE THREAD

**Issue by paulbfrench** [accanto-systems/openstack-vim-driver#52]
**Describe the bug**
The sample of using a string like `os_cacert` as described did not work for me when using the Swagger API `https://<host>:<port>/api/os/ui/#/openstack-locations/.ping`.

**To Reproduce**
Using the `Try it out` on the API, 
[A] This did not work, giving a `Bad Request , Request body is not valid JSON`
`
{
  "deploymentLocation": {
    "name": "test",
    "properties": {"os_auth_project_name": "admin",
"os_auth_project_domain_name": "Default",
"os_auth_password": "QmtJe43ExTm2sYCcrANGdTrnV",
"os_auth_username": "admin",
"os_auth_user_domain_name": "Default",
"os_auth_api": "v3",
"os_api_url": "https://9.20.133.31:13000",
"packageRepositoryUrl": "http://9.30.118.175:32739",
"os_cacert": |
  -----BEGIN CERTIFICATE-----
  MIIF4TCCA8mgAwIBAgIJAMn3Ningiqw3MA0GCSqGSIb3DQEBCwUAMIGGMQswCQYD
  VQQGEwJVSzEQMA4GA1UECAwHSHVyc2xleTENMAsGA1UEBwwEY2l0eTEMMAoGA1UE
  CgwDSUJNMQ4wDAYDVQQLDAVUZWxjbzEUMBIGA1UEAwwLOS4yMC4xMzMuMzExIjAg
  BgkqhkiG9w0BCQEWE2Rhc3VyZXNoQGluLmlibS5jb20wHhcNMjAwMzI1MTQ1ODIy
  WhcNNDAwMzIwMTQ1ODIyWjCBhjELMAkGA1UEBhMCVUsxEDAOBgNVBAgMB0h1cnNs
  ZXkxDTALBgNVBAcMBGNpdHkxDDAKBgNVBAoMA0lCTTEOMAwGA1UECwwFVGVsY28x
  FDASBgNVBAMMCzkuMjAuMTMzLjMxMSIwIAYJKoZIhvcNAQkBFhNkYXN1cmVzaEBp
  bi5pYm0uY29tMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAxEgKkJcC
  nE/tW/6DAnpKNeZqxTf7Sp76RVLPsBjpb3ZluP+hPi8+KUH132udShz3H6tSzMJj
  xWe3+V3FvdGjyDyw80k6q7OheNjCKiqRjlWOMQIK0xheeE2PEajzN+8+lkdTknir
  C1G7xmrfDsfe7Bl/s8LMkigkwirpo8WGRktYO5YvrHkimJSNcQJXyoJNLcTjc96x
  bZDZ8OBtTJuHSksyKsxMoNUgpQB29KU7lm4QZ/qNQQp4954/L6EgKpWZZgCqh5V3
  f81zb1kP1TJIWMVf0Y6qn4EzE37lO7UhyyyeQy/AcYreRC+xEJd1rf2bc1MJK6kB
  IB/vGlnEfRyUSqdCxLCCJ7rzkOPyleJ0OVpWyA2kha27/6Dw3uyqivMwNg3pL/0l
  Q0VvEFKXB350LpbJA+1PvPpTEH5JPnasS7BZYXrzGkY0p0E/Mm8T5aW4Hrp9YZk0
  9IEjcckCLP3kHAMmGGRtUsOX79KZWW+pOUpQoxMkONtqZYotoR90DNAW2MvX5hq+
  DUvPbQFOV7+i/IlSPGelGqvl753/ymcItBeq5CGgNa+QMZlkVTWCsqg7YTFartU/
  JA5DIkQMH+a1j4B3AyH/DP1XQxzxFg2tOVGiJfGnbKhuhTkaDAMiTBNYZJxPtQU/
  1yI79c65IhTC2BtubTRLyzE/V5xHlkTOMm0CAwEAAaNQME4wHQYDVR0OBBYEFKaC
  zsOyTtFBPzECa4bSTmDakZODMB8GA1UdIwQYMBaAFKaCzsOyTtFBPzECa4bSTmDa
  kZODMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBAJ708FpXiounmZgZ
  l6ZOeXMiMvYxgHQIycI1dvl53eRBc6qt8qjzZY8N51r4xMZExhJNo+U86A2tkuqf
  i09XbXyqx/gA5mRUln0vJA8qGxmWRqzRv/sAAa66uzKnU+2qGMhTpVPuIUm3QBde
  JajgZHUSazsUhJt/UnZic1VUQaIi1ZKYGIUBnrvI9rQW7PHKaPxGdIHOK1yIyjn0
  oVj7+NBUN6fdxcN3NdYAJM/ec/B23y2ZCid3USS319SDyniRf/pqxIkw6z+D3okt
  8DiVcTkVCy/46c7WnD/Gg+/tJXJpIi/UnpoPqIFpCt4kFrMdh3Ezni0HuurrTG03
  6eUK7+jGeYIBQINGwDTRHWpXPCoPiivEjijuSiR1Lnps+R+UTwnGeR5IpibS/jnm
  uReTovMijIi5mNX1qCHxG25SzWFyIoSBA/n/0OJnZ1T4HHaovvr57CpVP0L2Haj+
  UqZsgxPiA9GrM6kTiZvS01qQjR5j7olrNwns+XqE7W26OTGtyy11MCevlZ0Vanz7
  pQ7ORIx8UtmCYTR7DN4LZ5MFvZyMUrmfiaqu1LFxM5NsptbWhBjRQ+UDv8w4Laqe
  d68cOIlCm4Hk6a5WYLySYHb2NJnqurH2HILkBQhnTD46gs3ZTW/FY1RY+3EaRVwd
  0FN3Ar+C2UD4U43fSnoCJEqAk5YW
  -----END CERTIFICATE-----},
    "type": "string"
  }
}`

[B] This worked, using `os_cacert` as a string 
(btw,this is the cmd I used to stringify the .pem but I'm sure that there are other ways)

`awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}' ca_crt.pem > ca_crt.string`

`
{
  "deploymentLocation": {
    "name": "test",
    "properties": {"os_auth_project_name": "admin",
"os_auth_project_domain_name": "Default",
"os_auth_password": "QmtJe43ExTm2sYCcrANGdTrnV",
"os_auth_username": "admin",
"os_auth_user_domain_name": "Default",
"os_auth_api": "v3",
"os_api_url": "https://9.20.133.31:13000",
"packageRepositoryUrl": "http://9.30.118.175:32739",
"os_cacert": "-----BEGIN CERTIFICATE-----\nMIIF4TCCA8mgAwIBAgIJAMn3Ningiqw3MA0GCSqGSIb3DQEBCwUAMIGGMQswCQYD\nVQQGEwJVSzEQMA4GA1UECAwHSHVyc2xleTENMAsGA1UEBwwEY2l0eTEMMAoGA1UE\nCgwDSUJNMQ4wDAYDVQQLDAVUZWxjbzEUMBIGA1UEAwwLOS4yMC4xMzMuMzExIjAg\nBgkqhkiG9w0BCQEWE2Rhc3VyZXNoQGluLmlibS5jb20wHhcNMjAwMzI1MTQ1ODIy\nWhcNNDAwMzIwMTQ1ODIyWjCBhjELMAkGA1UEBhMCVUsxEDAOBgNVBAgMB0h1cnNs\nZXkxDTALBgNVBAcMBGNpdHkxDDAKBgNVBAoMA0lCTTEOMAwGA1UECwwFVGVsY28x\nFDASBgNVBAMMCzkuMjAuMTMzLjMxMSIwIAYJKoZIhvcNAQkBFhNkYXN1cmVzaEBp\nbi5pYm0uY29tMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAxEgKkJcC\nnE/tW/6DAnpKNeZqxTf7Sp76RVLPsBjpb3ZluP+hPi8+KUH132udShz3H6tSzMJj\nxWe3+V3FvdGjyDyw80k6q7OheNjCKiqRjlWOMQIK0xheeE2PEajzN+8+lkdTknir\nC1G7xmrfDsfe7Bl/s8LMkigkwirpo8WGRktYO5YvrHkimJSNcQJXyoJNLcTjc96x\nbZDZ8OBtTJuHSksyKsxMoNUgpQB29KU7lm4QZ/qNQQp4954/L6EgKpWZZgCqh5V3\nf81zb1kP1TJIWMVf0Y6qn4EzE37lO7UhyyyeQy/AcYreRC+xEJd1rf2bc1MJK6kB\nIB/vGlnEfRyUSqdCxLCCJ7rzkOPyleJ0OVpWyA2kha27/6Dw3uyqivMwNg3pL/0l\nQ0VvEFKXB350LpbJA+1PvPpTEH5JPnasS7BZYXrzGkY0p0E/Mm8T5aW4Hrp9YZk0\n9IEjcckCLP3kHAMmGGRtUsOX79KZWW+pOUpQoxMkONtqZYotoR90DNAW2MvX5hq+\nDUvPbQFOV7+i/IlSPGelGqvl753/ymcItBeq5CGgNa+QMZlkVTWCsqg7YTFartU/\nJA5DIkQMH+a1j4B3AyH/DP1XQxzxFg2tOVGiJfGnbKhuhTkaDAMiTBNYZJxPtQU/\n1yI79c65IhTC2BtubTRLyzE/V5xHlkTOMm0CAwEAAaNQME4wHQYDVR0OBBYEFKaC\nzsOyTtFBPzECa4bSTmDakZODMB8GA1UdIwQYMBaAFKaCzsOyTtFBPzECa4bSTmDa\nkZODMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggIBAJ708FpXiounmZgZ\nl6ZOeXMiMvYxgHQIycI1dvl53eRBc6qt8qjzZY8N51r4xMZExhJNo+U86A2tkuqf\ni09XbXyqx/gA5mRUln0vJA8qGxmWRqzRv/sAAa66uzKnU+2qGMhTpVPuIUm3QBde\nJajgZHUSazsUhJt/UnZic1VUQaIi1ZKYGIUBnrvI9rQW7PHKaPxGdIHOK1yIyjn0\noVj7+NBUN6fdxcN3NdYAJM/ec/B23y2ZCid3USS319SDyniRf/pqxIkw6z+D3okt\n8DiVcTkVCy/46c7WnD/Gg+/tJXJpIi/UnpoPqIFpCt4kFrMdh3Ezni0HuurrTG03\n6eUK7+jGeYIBQINGwDTRHWpXPCoPiivEjijuSiR1Lnps+R+UTwnGeR5IpibS/jnm\nuReTovMijIi5mNX1qCHxG25SzWFyIoSBA/n/0OJnZ1T4HHaovvr57CpVP0L2Haj+\nUqZsgxPiA9GrM6kTiZvS01qQjR5j7olrNwns+XqE7W26OTGtyy11MCevlZ0Vanz7\npQ7ORIx8UtmCYTR7DN4LZ5MFvZyMUrmfiaqu1LFxM5NsptbWhBjRQ+UDv8w4Laqe\nd68cOIlCm4Hk6a5WYLySYHb2NJnqurH2HILkBQhnTD46gs3ZTW/FY1RY+3EaRVwd\n0FN3Ar+C2UD4U43fSnoCJEqAk5YW\n-----END CERTIFICATE-----\n"
},
    "type": "string"
  }
}`

**Expected behavior**
Response Body
`{
  "description": "Reached Heat client successfully",
  "success": true
}
`

**Screenshots**

**Environment: (please complete the following information where applicable):**
 - OS: Ubuntu 16.04
 - Version 1.0.0
 - Stratoss LM 2.1

**Additional context**
It is probably the same for other string which contains \n

**Comment by dvaccarosenna** [comment]
Good spot. The second example has been written in YAML whilst the first was in JSON - would be good to give both examples in both formats (one for users of the ping API and one for users creating deployment locations with lmctl). Will look to fix this ASAP.
